// Soft Signal style: light editorial finance UI, tactile neumorphism, semantic mint/coral/indigo accents, asymmetric dashboard canvas, calm motion.
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { motion, AnimatePresence } from "framer-motion";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, Bot, BriefcaseBusiness, CalendarDays, ChevronDown, CircleDollarSign, CreditCard, FileText, Filter, Goal, Grid2X2, HeartPulse, LayoutDashboard, Menu, Mic, MoreHorizontal, PiggyBank, Plus, ReceiptIndianRupee, Search, Settings2, Sparkles, Target, TrendingUp, UserRound, WalletCards, X, Zap
} from "lucide-react";
import { Button } from "@/components/ui/button";
import Logo from "@/components/Logo";

type Role = "student" | "professional";
type NavItem = { label: string; icon: React.ElementType };

const studentNav: NavItem[] = [
  { label: "Overview", icon: LayoutDashboard }, { label: "Pocket Money", icon: WalletCards }, { label: "Expenses", icon: ReceiptIndianRupee }, { label: "Budget", icon: Grid2X2 }, { label: "Semester Budget", icon: CalendarDays }, { label: "Project Expenses", icon: BriefcaseBusiness }, { label: "Savings Goals", icon: Goal }, { label: "Emergency Fund", icon: HeartPulse }, { label: "AI Insights", icon: Bot }, { label: "Analytics", icon: Activity }, { label: "Reports", icon: FileText }, { label: "Receipt Scanner", icon: ReceiptIndianRupee }, { label: "Voice Expense", icon: Mic }, { label: "Subscriptions", icon: CreditCard },
];
const professionalNav: NavItem[] = [
  { label: "Overview", icon: LayoutDashboard }, { label: "Income", icon: CircleDollarSign }, { label: "Expenses", icon: ReceiptIndianRupee }, { label: "Budget", icon: Grid2X2 }, { label: "Savings Goals", icon: Goal }, { label: "Emergency Fund", icon: HeartPulse }, { label: "Predictions", icon: TrendingUp }, { label: "AI Insights", icon: Bot }, { label: "Analytics", icon: Activity }, { label: "Reports", icon: FileText }, { label: "Receipt Scanner", icon: ReceiptIndianRupee }, { label: "Voice Expense", icon: Mic }, { label: "Subscriptions", icon: CreditCard },
];

const transactions = [
  { name: "Lunch at Green Bowl", category: "Food", date: "Today, 1:12 PM", amount: "−₹250", color: "coral" },
  { name: "Uber ride", category: "Travel", date: "Yesterday, 8:44 PM", amount: "−₹180", color: "cyan" },
  { name: "Books & stationery", category: "Education", date: "10 Aug, 4:20 PM", amount: "−₹850", color: "blue" },
  { name: "Movie night", category: "Entertainment", date: "09 Aug, 7:05 PM", amount: "−₹300", color: "pink" },
];

const trendBars = [36, 48, 44, 68, 58, 72, 62, 84, 70, 76, 61, 78];

function formatNumber(value: number) { return new Intl.NumberFormat("en-IN").format(value); }

export default function Home() {
  const [role, setRole] = useState<Role>("professional");
  const [active, setActive] = useState("Overview");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [showAdd, setShowAdd] = useState(false);
  const [showSearch, setShowSearch] = useState(false);
  const [query, setQuery] = useState("");
  const [expenseName, setExpenseName] = useState("");
  const [expenseAmount, setExpenseAmount] = useState("");
  const nav = role === "student" ? studentNav : professionalNav;
  const filteredTransactions = useMemo(() => transactions.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()) || item.category.toLowerCase().includes(query.toLowerCase())), [query]);
  const isStudent = role === "student";

  const switchRole = (next: Role) => {
    setRole(next); setActive("Overview");
    toast.success(`Switched to ${next === "student" ? "Student" : "Professional"} workspace`);
  };
  const submitExpense = () => {
    if (!expenseName || !expenseAmount) { toast.error("Add a name and amount first"); return; }
    toast.success(`${expenseName} added to your expenses`, { description: `₹${expenseAmount} · Food · UPI` });
    setExpenseName(""); setExpenseAmount(""); setShowAdd(false);
  };
  const handleNav = (label: string) => {
    setActive(label); setMobileOpen(false);
    if (label !== "Overview") toast.info(`${label} view is ready to explore`, { description: "This demo keeps your overview in focus." });
  };

  return (
    <div className="min-h-screen bg-[#f5f7f3] text-[#172532]">
      <aside className={`fixed inset-y-0 left-0 z-40 flex w-[264px] flex-col border-r border-[#e3e8e2] bg-[#f8faf7]/95 px-5 py-6 backdrop-blur-xl transition-transform duration-300 lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}>
        <div className="mb-9 flex items-center justify-between px-2">
          <button className="flex items-center gap-3 text-left" onClick={() => handleNav("Overview")} aria-label="AI Expense Tracker home">
            <Logo size="md" />
          </button>
          <button className="rounded-lg p-1 text-[#83918d] lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X size={18} /></button>
        </div>
        <div className="mb-5 rounded-2xl bg-[#eef3ee] p-1.5 shadow-[inset_2px_2px_7px_rgba(23,37,50,.08),inset_-2px_-2px_7px_rgba(255,255,255,.9)]">
          <div className="flex gap-1">
            {(["professional", "student"] as Role[]).map((item) => <button key={item} onClick={() => switchRole(item)} className={`flex-1 rounded-xl px-2 py-2 text-[11px] font-bold capitalize transition-all ${role === item ? "bg-white text-[#172532] shadow-[0_3px_8px_rgba(23,37,50,.1)]" : "text-[#87928b]"}`}>{item}</button>)}
          </div>
        </div>
        <p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.17em] text-[#96a19c]">Workspace</p>
        <nav className="space-y-1 overflow-y-auto pr-1">
          {nav.map(({ label, icon: Icon }, index) => <button key={label} onClick={() => handleNav(label)} className={`group flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[13px] font-semibold transition-all ${active === label ? "bg-[#172532] text-white shadow-[5px_7px_18px_rgba(23,37,50,.16)]" : "text-[#728079] hover:bg-white hover:text-[#172532] hover:shadow-[3px_4px_12px_rgba(23,37,50,.06)]"}`}><Icon size={17} strokeWidth={active === label ? 2.4 : 1.8} className={active === label ? "text-[#7BE2BE]" : "text-[#9aa6a0] group-hover:text-[#172532]"} /><span>{label}</span>{index === 8 && <span className="ml-auto rounded-full bg-[#e4dcff] px-1.5 py-0.5 text-[9px] font-bold text-[#6d5bb7]">AI</span>}</button>)}
        </nav>
        <div className="mt-auto space-y-1 pt-4"><button onClick={() => toast.info("Notifications are all caught up")} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-[13px] font-semibold text-[#728079] hover:bg-white"><Bell size={17} /> Notifications <span className="ml-auto h-2 w-2 rounded-full bg-[#f29b75]" /></button><button onClick={() => toast.info("Settings panel opened")} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-[13px] font-semibold text-[#728079] hover:bg-white"><Settings2 size={17} /> Settings</button><div className="mt-3 flex items-center gap-3 border-t border-[#e4eae5] px-3 pt-4"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#dbeee6] text-[12px] font-bold text-[#357963]">AR</div><div className="min-w-0"><p className="truncate text-[12px] font-bold">Aarav Rao</p><p className="text-[11px] text-[#98a39e]">{isStudent ? "Student account" : "Professional account"}</p></div><MoreHorizontal size={17} className="ml-auto text-[#a2aaa5]" /></div></div>
      </aside>
      {mobileOpen && <button className="fixed inset-0 z-30 bg-[#172532]/20 backdrop-blur-sm lg:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation" />}

      <main className="min-h-screen lg:pl-[264px]">
        <header className="sticky top-0 z-20 flex h-[76px] items-center justify-between border-b border-[#e6ebe6]/80 bg-[#f5f7f3]/90 px-5 backdrop-blur-xl sm:px-8 lg:px-10">
          <div className="flex items-center gap-3"><button className="rounded-xl bg-white p-2.5 text-[#172532] shadow-sm lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={19} /></button><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#9ba6a0]">{active === "Overview" ? "Monday, 16 August 2026" : "Workspace view"}</p><h1 className="font-display text-[19px] font-bold tracking-[-.04em]">{active === "Overview" ? "Good morning, Aarav" : active}</h1></div></div>
          <div className="flex items-center gap-2.5"><AnimatePresence>{showSearch && <motion.div initial={{ width: 0, opacity: 0 }} animate={{ width: 210, opacity: 1 }} exit={{ width: 0, opacity: 0 }} className="overflow-hidden"><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search transactions" className="h-10 w-[210px] rounded-xl border border-[#e2e8e1] bg-white px-3 text-[12px] outline-none ring-[#7BE2BE] focus:ring-2" /></motion.div>}</AnimatePresence><button onClick={() => setShowSearch((value) => !value)} className="grid h-10 w-10 place-items-center rounded-xl bg-white text-[#728079] shadow-[3px_4px_10px_rgba(23,37,50,.06)] transition hover:-translate-y-0.5 hover:text-[#172532]" aria-label="Search"><Search size={18} /></button><button onClick={() => toast.info("You have 3 new insights")} className="relative grid h-10 w-10 place-items-center rounded-xl bg-white text-[#728079] shadow-[3px_4px_10px_rgba(23,37,50,.06)] transition hover:-translate-y-0.5 hover:text-[#172532]" aria-label="Notifications"><Bell size={18} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[#f29b75]" /></button><button onClick={() => toast.info("Profile settings ready")} className="hidden items-center gap-2 rounded-xl bg-white px-2 py-1.5 shadow-[3px_4px_10px_rgba(23,37,50,.06)] sm:flex"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#dbeee6] text-[10px] font-bold text-[#357963]">AR</span><ChevronDown size={14} className="text-[#9ba6a0]" /></button></div>
        </header>

        <div className="mx-auto max-w-[1440px] px-5 pb-12 pt-7 sm:px-8 lg:px-10">
          {active !== "Overview" && <div className="mb-6 rounded-[24px] border border-[#e1e8e2] bg-white p-7 shadow-[0_14px_35px_rgba(42,65,55,.05)]"><div className="flex items-start justify-between"><div><span className="mb-3 inline-flex rounded-full bg-[#e8f8f0] px-3 py-1 text-[10px] font-bold uppercase tracking-[.13em] text-[#32795d]">{role} workspace</span><h2 className="font-display text-3xl font-bold tracking-[-.05em]">{active}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#7b8982]">Your {active.toLowerCase()} tools live here. The demo is wired for interaction so you can explore the full information architecture without leaving the dashboard.</p></div><div className="hidden rounded-2xl bg-[#f0f6f1] p-4 sm:block"><Sparkles className="text-[#5db994]" size={24} /></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#f7faf7] p-4"><p className="text-[11px] text-[#93a09a]">Quick action</p><p className="mt-1 text-sm font-bold">Add an expense</p></div><div className="rounded-2xl bg-[#f7faf7] p-4"><p className="text-[11px] text-[#93a09a]">Latest update</p><p className="mt-1 text-sm font-bold">₹2,180 saved this month</p></div><div className="rounded-2xl bg-[#f7faf7] p-4"><p className="text-[11px] text-[#93a09a]">Next best action</p><p className="mt-1 text-sm font-bold">Review your {isStudent ? "semester" : "monthly"} budget</p></div></div></div>}
          <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-[#e7f8ef] px-3 py-1 text-[10px] font-bold uppercase tracking-[.14em] text-[#3b8165]"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#55c797]" /> Your money at a glance</div><h2 className="max-w-[620px] font-display text-[31px] font-bold leading-[1.08] tracking-[-.06em] sm:text-[40px]">A calmer way to stay <span className="text-[#4bbf90]">ahead.</span></h2><p className="mt-3 max-w-[560px] text-[13px] leading-6 text-[#82908a]">Understand your spending, find your next best move, and keep the month feeling comfortable.</p></div><Button onClick={() => setShowAdd(true)} className="group h-11 rounded-xl bg-[#172532] px-4 text-[12px] font-bold text-white shadow-[6px_8px_18px_rgba(23,37,50,.14)] transition hover:-translate-y-0.5 hover:bg-[#243b4a]"><Plus size={17} className="mr-2 text-[#7BE2BE] transition group-hover:rotate-90" /> Add expense</Button></div>

          <div className="grid gap-5 xl:grid-cols-[1.55fr_1fr_1fr]">
            <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }} className="relative min-h-[238px] overflow-hidden rounded-[26px] bg-[#172532] p-7 text-white shadow-[10px_14px_35px_rgba(23,37,50,.16)]"><img src="/manus-storage/soft-signal-hero_442e743e.png" alt="" className="pointer-events-none absolute inset-0 h-full w-full object-cover opacity-30 mix-blend-screen" /><div className="relative z-10 flex h-full flex-col justify-between"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#a5b9b0]">{isStudent ? "Pocket money remaining" : "Monthly savings"}</p><p className="mt-3 font-display text-[42px] font-bold tracking-[-.07em]">{isStudent ? "₹18,450" : "₹32,800"}</p></div><div className="rounded-xl bg-white/10 p-2.5"><PiggyBank className="text-[#7BE2BE]" size={20} /></div></div><div><div className="mb-2 flex items-center justify-between text-[11px] text-[#a5b9b0]"><span>{isStudent ? "63% of monthly pocket money" : "34% savings rate"}</span><span className="font-bold text-[#d6eee4]">{isStudent ? "63%" : "34%"}</span></div><div className="h-2 rounded-full bg-white/10"><motion.div initial={{ width: 0 }} animate={{ width: isStudent ? "63%" : "34%" }} transition={{ delay: .35, duration: .9, ease: [0.23,1,0.32,1] }} className="h-full rounded-full bg-[#7BE2BE]" /></div><p className="mt-3 text-[11px] text-[#a5b9b0]">{isStudent ? "₹1,220 safe to spend each day" : "₹5,200 more than your target"}</p></div></div></motion.section>
            {[{ label: isStudent ? "Total spending" : "Total expenses", value: isStudent ? "₹11,550" : "₹62,480", delta: "8.4%", positive: false, icon: ArrowDownRight, tone: "coral" }, { label: isStudent ? "Financial health" : "Financial health score", value: "78 / 100", delta: "Good", positive: true, icon: HeartPulse, tone: "mint" }].map((card, index) => <motion.section key={card.label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 * (index + 1), duration: .45 }} className="rounded-[26px] bg-white p-6 shadow-[6px_9px_23px_rgba(42,65,55,.07)]"><div className="flex items-start justify-between"><span className={`grid h-10 w-10 place-items-center rounded-[13px] ${card.tone === "coral" ? "bg-[#fff0eb] text-[#e98b68]" : "bg-[#e7f8ef] text-[#41aa7e]"}`}><card.icon size={19} /></span><button onClick={() => toast.info("Metric details are available in Analytics")}><MoreHorizontal size={18} className="text-[#a3aea8]" /></button></div><p className="mt-7 text-[12px] font-semibold text-[#849089]">{card.label}</p><p className="mt-1 font-display text-[28px] font-bold tracking-[-.06em]">{card.value}</p><div className="mt-3 flex items-center gap-1.5 text-[11px] font-bold"><span className={card.positive ? "text-[#4aaf82]" : "text-[#e68767]"}>{card.positive ? "↑" : "↓"} {card.delta}</span><span className="font-medium text-[#a2aca7]">vs last month</span></div></motion.section>)}
          </div>

          <div className="mt-5 grid gap-5 xl:grid-cols-[1.42fr_1fr]">
            <section className="rounded-[26px] bg-white p-6 shadow-[6px_9px_23px_rgba(42,65,55,.07)] sm:p-7"><div className="mb-7 flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#9aa69f]">Spending pulse</p><h3 className="mt-1 font-display text-[21px] font-bold tracking-[-.05em]">Monthly expense trend</h3></div><button onClick={() => toast.info("Showing last 12 months")} className="flex items-center gap-2 rounded-xl bg-[#f5f8f4] px-3 py-2 text-[11px] font-bold text-[#738079]">This year <ChevronDown size={14} /></button></div><div className="flex h-[185px] items-end gap-2 sm:gap-4">{trendBars.map((height, index) => <div key={index} className="group flex h-full flex-1 flex-col justify-end"><div className={`relative w-full rounded-t-[8px] transition-all duration-300 group-hover:-translate-y-1 ${index === 7 ? "bg-[#172532]" : "bg-[#d9f1e6]"}`} style={{ height: `${height}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 text-[9px] font-bold text-[#5b6a62] group-hover:block">₹{Math.round(height * 420)}</span></div><span className="mt-3 text-center text-[10px] text-[#a1aaa5]">{["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][index]}</span></div>)}</div></section>
            <section className="relative overflow-hidden rounded-[26px] bg-[#eef3ff] p-6 shadow-[6px_9px_23px_rgba(42,65,55,.05)] sm:p-7"><div className="absolute -right-7 -top-10 h-36 w-36 rounded-full bg-[#d9d4ff] blur-2xl" /><div className="relative"><div className="flex items-center justify-between"><div className="flex items-center gap-2 rounded-full bg-white/70 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.12em] text-[#695db3]"><Sparkles size={13} /> AI note</div><span className="text-[11px] font-semibold text-[#8c8bb3]">Just now</span></div><h3 className="mt-6 max-w-[280px] font-display text-[22px] font-bold leading-tight tracking-[-.05em] text-[#28364c]">Small shift, bigger breathing room.</h3><p className="mt-3 max-w-[320px] text-[12px] leading-6 text-[#717c95]">Your food expenses are 18% higher than last month. A ₹700 trim here could bring your savings rate back to target.</p><button onClick={() => { setActive("AI Insights"); toast.success("Insight saved to your workspace"); }} className="mt-6 flex items-center gap-2 text-[12px] font-bold text-[#5c52a5]">See recommendation <ArrowUpRight size={15} /></button><img src="/manus-storage/soft-signal-ai-illustration_27e3b90d.png" alt="" className="pointer-events-none absolute -bottom-7 -right-8 h-32 w-40 object-contain opacity-75" /></div></section>
          </div>

          <div className="mt-5 grid gap-5 xl:grid-cols-[1.1fr_1fr_1fr]">
            <section className="rounded-[26px] bg-white p-6 shadow-[6px_9px_23px_rgba(42,65,55,.07)]"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#9aa69f]">Budget health</p><h3 className="mt-1 font-display text-[21px] font-bold tracking-[-.05em]">Where your money goes</h3></div><button onClick={() => toast.info("Budget details opened")} className="rounded-xl bg-[#f7f9f6] p-2"><MoreHorizontal size={18} className="text-[#8b9891]" /></button></div><div className="mt-7 flex items-center gap-6"><div className="relative grid h-[126px] w-[126px] shrink-0 place-items-center rounded-full" style={{ background: "conic-gradient(#7BE2BE 0 34%, #a29bf4 34% 56%, #f6ae8e 56% 74%, #a9dced 74% 88%, #edf0ec 88% 100%)" }}><div className="grid h-[86px] w-[86px] place-items-center rounded-full bg-white"><div className="text-center"><p className="font-display text-[22px] font-bold">72%</p><p className="text-[9px] font-bold uppercase tracking-wider text-[#9ca8a1]">used</p></div></div></div><div className="space-y-3">{[["Food","₹21,240","#7BE2BE"],["Bills","₹13,740","#a29bf4"],["Travel","₹9,420","#f6ae8e"],["Other","₹8,080","#a9dced"]].map(([label, value, color]) => <div key={label} className="flex items-center gap-2.5"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: color }} /><span className="w-12 text-[11px] text-[#77847c]">{label}</span><span className="text-[11px] font-bold">{value}</span></div>)}</div></div></section>
            <section className="rounded-[26px] bg-[#fff8f3] p-6 shadow-[6px_9px_23px_rgba(42,65,55,.05)]"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#ad9584]">Emergency fund</p><h3 className="mt-1 font-display text-[21px] font-bold tracking-[-.05em]">A softer landing</h3></div><HeartPulse size={20} className="text-[#ed9b76]" /></div><div className="mt-6 flex items-end justify-between"><p className="font-display text-[30px] font-bold tracking-[-.06em]">₹60,000</p><p className="mb-1 text-[11px] font-bold text-[#d78a67]">2 months covered</p></div><div className="mt-3 h-2 rounded-full bg-[#f3e5dc]"><div className="h-full w-[67%] rounded-full bg-[#ed9b76]" /></div><div className="mt-2 flex justify-between text-[10px] text-[#b59d8d]"><span>Current</span><span>Recommended ₹90,000</span></div><button onClick={() => toast.success("Emergency fund contribution flow opened")} className="mt-5 text-[12px] font-bold text-[#c87855]">Add contribution <ArrowUpRight size={14} className="ml-1 inline" /></button></section>
            <section className="rounded-[26px] bg-[#eaf8f4] p-6 shadow-[6px_9px_23px_rgba(42,65,55,.05)]"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#73a291]">Savings goal</p><h3 className="mt-1 font-display text-[21px] font-bold tracking-[-.05em]">New laptop</h3></div><Target size={20} className="text-[#4caf89]" /></div><div className="mt-6 flex items-end justify-between"><p className="font-display text-[30px] font-bold tracking-[-.06em]">₹42,800</p><p className="mb-1 text-[11px] font-bold text-[#499876]">68% complete</p></div><div className="mt-3 h-2 rounded-full bg-[#cdeee1]"><div className="h-full w-[68%] rounded-full bg-[#4caf89]" /></div><div className="mt-2 flex justify-between text-[10px] text-[#81a99d]"><span>₹42,800 saved</span><span>₹20,200 left</span></div><button onClick={() => toast.success("Contribution added to New laptop")} className="mt-5 text-[12px] font-bold text-[#3c896c]">Add contribution <Plus size={14} className="ml-1 inline" /></button></section>
          </div>

          <section className="mt-5 rounded-[26px] bg-white p-6 shadow-[6px_9px_23px_rgba(42,65,55,.07)] sm:p-7"><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[.15em] text-[#9aa69f]">Latest activity</p><h3 className="mt-1 font-display text-[21px] font-bold tracking-[-.05em]">Recent transactions</h3></div><div className="flex gap-2"><button onClick={() => setQuery("")} className="flex items-center gap-2 rounded-xl bg-[#f5f8f4] px-3 py-2 text-[11px] font-bold text-[#718078]"><Filter size={14} /> Filter</button><button onClick={() => toast.info("All transactions opened")} className="rounded-xl px-3 py-2 text-[11px] font-bold text-[#4a9b78]">View all</button></div></div><div className="divide-y divide-[#eef1ed]">{filteredTransactions.length ? filteredTransactions.map((item) => <div key={item.name} className="group flex items-center justify-between gap-4 py-4 first:pt-1"><div className="flex min-w-0 items-center gap-3"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${item.color === "coral" ? "bg-[#fff0eb] text-[#e68c6c]" : item.color === "cyan" ? "bg-[#e7f7fa] text-[#55a9bc]" : item.color === "blue" ? "bg-[#eaf0ff] text-[#738ce2]" : "bg-[#ffeaf1] text-[#de759b]"}`}><CircleDollarSign size={17} /></div><div className="min-w-0"><p className="truncate text-[13px] font-bold">{item.name}</p><p className="mt-1 text-[11px] text-[#9ba59f]">{item.category} · {item.date}</p></div></div><p className="shrink-0 text-[13px] font-bold text-[#df7f64]">{item.amount}</p></div>) : <div className="py-10 text-center text-sm text-[#8c9891]">No transactions match “{query}”.</div>}</div></section>
        </div>
      </main>

      <AnimatePresence>{showAdd && <motion.div className="fixed inset-0 z-50 grid place-items-center bg-[#172532]/25 p-4 backdrop-blur-sm" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.div initial={{ opacity: 0, scale: .96, y: 12 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: .96, y: 12 }} className="w-full max-w-md rounded-[26px] bg-[#f9fbf8] p-6 shadow-[0_20px_60px_rgba(23,37,50,.2)]"><div className="flex items-start justify-between"><div><span className="inline-flex rounded-full bg-[#e7f8ef] px-3 py-1 text-[10px] font-bold uppercase tracking-[.14em] text-[#3b8165]">Quick entry</span><h3 className="mt-3 font-display text-2xl font-bold tracking-[-.05em]">Add an expense</h3><p className="mt-1 text-[12px] text-[#8b9891]">Capture it now. Keep the bigger picture clear.</p></div><button onClick={() => setShowAdd(false)} className="rounded-xl bg-white p-2 text-[#82908a]"><X size={17} /></button></div><div className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-[11px] font-bold text-[#76837b]">What did you spend on?</span><input value={expenseName} onChange={(e) => setExpenseName(e.target.value)} placeholder="e.g. Lunch at Green Bowl" className="h-12 w-full rounded-xl border border-[#e2e9e2] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#b8ecd6]" /></label><label className="block"><span className="mb-2 block text-[11px] font-bold text-[#76837b]">Amount</span><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm font-bold text-[#8a978f]">₹</span><input type="number" value={expenseAmount} onChange={(e) => setExpenseAmount(e.target.value)} placeholder="0" className="h-12 w-full rounded-xl border border-[#e2e9e2] bg-white pl-8 pr-3 text-sm outline-none focus:ring-2 focus:ring-[#b8ecd6]" /></div></label><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#f0f5ef] p-3"><p className="text-[10px] text-[#8d9992]">Category</p><p className="mt-1 text-[12px] font-bold">Food <ChevronDown size={13} className="ml-1 inline" /></p></div><div className="rounded-xl bg-[#f0f5ef] p-3"><p className="text-[10px] text-[#8d9992]">Payment method</p><p className="mt-1 text-[12px] font-bold">UPI <ChevronDown size={13} className="ml-1 inline" /></p></div></div></div><button onClick={submitExpense} className="mt-6 h-12 w-full rounded-xl bg-[#172532] text-[12px] font-bold text-white shadow-lg transition hover:bg-[#294353] active:scale-[.98]">Save expense <Zap size={14} className="ml-1 inline text-[#7BE2BE]" /></button></motion.div></motion.div>}</AnimatePresence>
      <button onClick={() => setShowAdd(true)} className="fixed bottom-5 right-5 z-20 grid h-12 w-12 place-items-center rounded-2xl bg-[#172532] text-white shadow-[0_10px_28px_rgba(23,37,50,.22)] transition hover:-translate-y-1 lg:hidden" aria-label="Add expense"><Plus size={21} className="text-[#7BE2BE]" /></button>
    </div>
  );
}
